#!/usr/bin/env python3

import sys
from jsoncrypt import *

if "display" in sys.argv and len(sys.argv) > 2:
    sys.argv.remove("display")
    filename = sys.argv[1]
    print(Encrypt.jsonfile(filename))
elif "help" in sys.argv or "-h" in sys.argv or "-help" in sys.argv:
    print("Json encryption with password")
    print("Usage:")
    print("display filename_path      -> To display the encryption of a file without changing the file")
    print("help | -h | -help          -> To see these options")
    print("-p filename_path passowrd  -> To encrypt a file with a password")
    print("json-encrypt filename_path -> To encrypt a file without a password") 
elif len(sys.argv) >= 2:
    if "-p" in sys.argv and len(sys.argv) >= 4:
        sys.argv.remove("-p")
        filename = sys.argv[1]
        password = sys.argv[2]
        if Encrypt.jsonfile(filename, save_file=True, password=password):
            print("Successfully encrypted with password")
        else:
            print("Failed to encrypt file {}".format(filename))
    else:
        filename = sys.argv[1]
        if Encrypt.jsonfile(filename, save_file=True):
            print("Successfully encrypt")
        else:
            print("Failed to encrypt file {}".format(filename))
